### PR TITLE
Design frames & styling edits

### PR DESCRIPTION
**Pull request by katehmay**
Hey Mikka,

I've finished the design wireframes and uploaded all of their PDFs. I did make a few major changes to two pages:

GET INVOLVED/PROJECTS:
I did end up having to just change this to projects, removing the latest events and putting that on its own page, for a couple of reasons. 

1, From a UX perspective, the navigation to this page didn't make much sense. From the homepage, you would click "learn more" for the projects section, only to be taken to the projects page that didn't have much information on the projects themselves, just a bio, with another learn more link that linked outwards again. It was redundant, and I came up with a solution: I took pertinent info from the actual individual pages for the projects and merged it into the projects page, with a link that would link down into a # href section. Both the top projects page and the homepage projects section can link down into this a # href section. And the project info actually wasn't too much to handle to put on the projects page anyway. In my opinion it just kind of made more sense to bring it to the projects page entirely and makes for a better user experience for someone trying to navigate to this information. The past projects, because they are not immediately relevant anymore, would link to an archive as they do on the original anglers website. Let me know if this all makes sense. It should be clearer if you take a look at the PDF itself.

2, I removed the events section and made it its own page because upon navigating the original website, there actually isn't much of a news section. There is the one 'latest news' on the homepage, but that's it. It's not enough content to fill and entire page. Which brings me to the next major change....

NEWS/EVENTS:

Like I said, I changed the news page to an events page mainly because it didn't make sense for me as the designer to have a news page. That, and when I was comparing our wireframe to the original site more closely, I realized that we had completely missed having a past events section entirely. This would have made the projects/get involved page way too convoluted to have all this information on one page, particularly since the past events section is quite long – it ended up being our longest page. Not hard to code as its just repeating elements, but long all the same, which makes a difficult navigation, so I came up for a solution for that as well. I only included the last 2-3 years of past events on the page, sectioned out with a sub navigation that would take you between each year, with a link to an archive of any event older than 2017. I hope that makes the navigation of that section a little easier from a UX perspective.

Anyway I'm pretty tired and have stopped seeing the design objectively haha so if you have any feedback let me know. We're at the stage where time is running out so we can't make any major changes at this time but if there is something I missed, feel free to point it out.

I also updated all the navs on each page to reflect the updated navigation on the pages, and I had a little glitch going on with my footer as well that I addressed and fixed.

### CODE REVIEW

**Comment by katehmay** [comment]
Oh, also, looks like I made a mistake and accidentally named the resource wireframe as newsletter. Disregard that. It is supposed to be resources.

**Comment by mazores** [comment]
Hey Kateh,

1. Bringing the content to the project pages entirely and having it linked down to the bottom is a good idea. Thank you for that. Initially had it linked out because I didn't think of cutting down the info for each project. 

2. Upon reviewing the TRAA website, their homepage acted as some announcements board for their members where they could find important dates and such. That's why the Events section in the homepage wireframe do not have a learn more button for each (sorry I forgot to point that out earlier) as their upcoming events seemed to just have short content? Instead we can just put a button to the Events page you created. What do you think?

As for the News section in the homepage, this is where they put their announcements such as new TRAA gear or the Trout Hatchery post. We can remove the Learn More button, similar to why the Events doesn't have a Learn More button as the button was initially to lead to the News Page.

As for the News page, I had that as a "blog" page for putting the past events but I think that what you did was a better solution. I completely see what you meant by the News/Announcements not being enough to fill a page. Thank you again for that!

As for the sub navigation, does that mean that each year would act like a pagination and clicking on it would change the articles to the year? Cause the design had them stacked up and I just wanted to clarify them!

**Comment by mazores** [comment]
Forgot to add, this is all okay with me! :)

**Comment by katehmay** [comment]
Awesome, and yes, those changes to the homepage make sense to me as well, go ahead and change that when you code things :)

And yup that's exactly it. It's all stacked up but you can easily click through each section by pagination.

**Comment by mazores** [comment]
Will do! Thanks, Kateh!

**Pull request merged**
